version: '3.7'
services:
  bot:
    build: .
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
